resin-udevmount: add udev rules for resin ubifs partition layout
resin-os/resin-chip pull request #17
Opened 2017-07-13 15:31 UTC by michal-mazurek

2017-07-13 15:35 UTC, agherzan commented on layers/meta-resin-chip/recipes-support/resin-udevmount/resin-udevmount.bb
> +LICENSE = "CLOSED"
We need to clarify this license. We can't use closed source code.

2017-07-13 15:36 UTC, agherzan commented on layers/meta-resin-chip/recipes-support/resin-udevmount/resin-udevmount.bb
> +PR = "r1"
We add a new recipe so PR r0 should be the first revision which is the default value so we can remove it altogether.

2017-07-13 15:36 UTC, agherzan requested changes

2017-07-13 15:36 UTC, agherzan commented on layers/meta-resin-chip/recipes-support/resin-udevmount/resin-udevmount.bb
> +FILES_${PN} += " \
No need to split the line here - we only have one entry.

2017-07-14 07:12 UTC, floion approved these changes

2017-07-14 07:12 UTC, merged